"""create_initial_schema

Revision ID: 2453de19b08e
Revises: 
Create Date: 2025-01-23 17:27:22.563941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2453de19b08e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('net_amount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('vat_amount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('vat_rate', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('package_type', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('project_limit', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notes')
    op.drop_column('subscriptions', 'end_date')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'project_limit')
    op.drop_column('subscriptions', 'package_type')
    op.drop_column('invoices', 'currency')
    op.drop_column('invoices', 'vat_rate')
    op.drop_column('invoices', 'vat_amount')
    op.drop_column('invoices', 'net_amount')
    # ### end Alembic commands ###
